#!/data/data/com.termux/files/usr/bin/bash


# Tools Auto NIK & KK

# Coded By c0day4t

# https://18yatstory.home.blog/

# 181204


# Bersihkan Layar

clear


#This colour

blue='\e[0;34'

cyan='\e[0;36m'

green='\e[0;34m'

okegreen='\033[92m'

lightgreen='\e[1;32m'

white='\e[1;37m'

red='\e[1;31m'

yellow='\e[1;33m'


###################################################

# CTRL C

###################################################

trap ctrl_c INT

ctrl_c() {

clear

echo -e $red"[#]> (Ctrl + C ) Detected, Trying To Exit ... "

sleep 1

echo ""

echo -e $yellow"[#]> Thank You For Using My Tools ... "

sleep 1

echo ""

echo -e $white"[#]> D4Y47 Wuzz Here ... "

read enter

exit

}


# Isi oc :*

echo -e $cyan
"
  ____ ___  ____    _   __   ___  _ _____
 / ___/ _ \|  _ \  / \  \ \ / / || |_   _|
| |  | | | | | | |/ _ \  \ V /| || |_| |
| |__| |_| | |_| / ___ \  | | |__   _| |
 \____\___/|____/_/   \_\ |_|    |_| |_|"





echo -e $white" ***********************************************"

echo -e $white" # #"

echo -e $white" # $cyan Toolkit For$red Lazy People$white #"

echo -e $white" # $cyan Author :$red c0day4t$white #"

echo -e $white" # $cyan Follow Me On Github:$red @codayid$white #"

echo -e $white" # $cyan My Blog:$red https://18yatstory.home.blog/$white #"

echo -e $white" # $cyan Contact Me In:$red +62 888-0928-0542$white #"

echo -e $white" # $cyan Changelog: $red 03-04-2019 $white #"

echo -e $white" # $cyan Team: $red Anon Cyber Team$white #"

echo -e $white" # #"

echo -e $white" ***********************************************"

echo ""

echo -e $red " 01) LANJUTKAN..."

echo -e $red " 02) KELUAR..."

echo -e $white ""

read -p "[c0day4t@Tools]> " act;

if [ $act = 1 ] || [ $act = 01 ]

then

clear



echo -e $white" ***********************************************"

echo -e $white" # #"

echo -e $white" # $red KK =>$red 3304080103070030$white #"

echo -e $white" # $white NIK =>$red 3304084102590002$white #"

echo -e $white" # #"

echo -e $white" ***********************************************"

echo ""

echo -e $white" ***********************************************"

echo -e $white" # #"

echo -e $white" # $red KK =>$red 3326163009050007$white #"

echo -e $white" # $white NIK =>$red 3326165012420001$white #"

echo -e $white" # #"

echo -e $white" ***********************************************"

echo ""

echo -e $white" ***********************************************"

echo -e $white" # #"

echo -e $white" # $red KK =>$red 3326160608070467$white #"

echo -e $white" # $white NIK =>$red 3326166205050003$white #"

echo -e $white" # #"

echo -e $white" ***********************************************"

echo ""

echo -e $white" ***********************************************"

echo -e $white" # #"

echo -e $white" # $red KK =>$red 3326161712050006$white #"

echo -e $white" # $white NIK =>$red 3326165908860001$white #"

echo -e $white" # #"

echo -e $white" ***********************************************"

echo ""

echo -e $red" ***********************************************"

echo -e $red" # #"

echo -e $red" # $white <<< UPDATE AKAN SELALU ADA >>> $red #"

echo -e $red" # $white <<< GUNAKAN NIK & KK DENGAN BAIK >>>$red #"

echo -e $red" # #"

echo -e $red" ***********************************************"

echo ""

fi

if [ $act = 2 ] || [ $act = 02 ]

then

echo " Proses Keluar... "

sleep 1

echo " copyright # AnonCyberTeam "

sleep 1

echo " Pergunakan Tools Yang Tersedia Dengan Bijak... "

sleep 1

echo -e $red " .............................................................. "

sleep 1

echo -e $yellow" .............................................................. "

sleep 1

echo -e $green " .............................................................. "

sleep 1

echo " ExCellent  : Arya Narotama X Muhammad Hidayat "

sleep 1

echo "  #AnonCyberTeam #INDONESIANHACKERRULEZ "

sleep 1

exit

fi
